# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: "Restore SpotSync"
  inputs:
    command: 'restore'
    projects: '**/SpotSync.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: "Build SpotSync"
  inputs:
    command: 'build'
    projects: '**/SpotSync.csproj'
- task: DotNetCoreCLI@2
  displayName: "Publish SpotSync"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: false
- task: DotNetCoreCLI@2
  displayName: "Test SpotSync"
  inputs:
    command: 'test'
    projects: '**/SpotSync.Tests.csproj'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SpotSync-Server'
    publishLocation: 'Container'